name: Update Schedule ICS File

# Run the action every hour
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour (at the top of the hour)

  workflow_dispatch: # Allows manual trigger

jobs:
  update-ics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Use the latest Python 3.x version

      - name: Install required Python packages
        run: |
          pip install requests
          pip install beautifulsoup4
          pip install ics

      - name: Run the script to generate schedule.ics
        run: |
          python scripts/generate_schedule.py

      - name: Commit and push the updated .ics file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add schedule.ics
          git commit -m "Update schedule.ics"
          git push
        env:
          # Set this environment variable to push changes back to the repository
          # GITHUB_TOKEN is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
